### ISSUE TITLE
After a daily rotation on IIS, bitfan stopped sending logs

### ISSUE THREAD

**Issue by immort4tor** [AlexAkulov/bitfan#4]
time="2017-10-26T17:42:03+05:00" level=warning msg="[file] sincedb not found: \"C:\\\\Program Files\\\\bitfan\\\\data\\\\input_file\\\\.sincedb.json\"" Xprocessor=file agent="input_file" pipeline=simple 
time="2017-10-26T17:42:03+05:00" level=info msg="[file] Seeked C:/inetpub/logs/LogFiles/W3SVC1/u_ex171026.log - &{Offset:0 Whence:2}\n" Xprocessor=file agent="input_file" pipeline=simple 
time="2017-10-27T01:00:30+05:00" level=info msg="[file] Re-opening moved/deleted file C:/inetpub/logs/LogFiles/W3SVC1/u_ex171026.log ..." Xprocessor=file agent="input_file" pipeline=simple 
time="2017-10-27T01:00:30+05:00" level=info msg="[file] Waiting for C:/inetpub/logs/LogFiles/W3SVC1/u_ex171026.log to appear..." Xprocessor=file agent="input_file" pipeline=simple

**Comment by AlexAkulov** [comment]
done
